# Cloudflare Pages Functions configuration
name = "sarkarisalaryde"
compatibility_date = "2024-10-24"

[env.production]
[[env.production.kv_namespaces]]
binding = "JOBS_KV"
id = "your-kv-namespace-id-here"
preview_id = "your-preview-kv-namespace-id-here"

[env.development]
[[env.development.kv_namespaces]]
binding = "JOBS_KV"
id = "your-dev-kv-namespace-id-here"
preview_id = "your-dev-preview-kv-namespace-id-here"